config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'
  
  get 'about' =>  'pages#about'
  
  devise_for :users
  resources :listings

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :listings
end

app/models/listing.rb
class Listing < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :listings, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
    before_action :find_listing, only: [:show, :edit, :update, :destroy]
    
    def index
    	if params[:category].blank?
			  @listings = Listing.all.order("created_at DESC")
		  else
			  @category_id = Category.find_by(name: params[:category]).id
			  @listings = Listing.where(:category_id => @category_id).order("created_at DESC")
		  end
    end
    
    def show
    end
    
    def new
      @listing = current_user.listings.build
      @categories = Category.all.map{ |c| [c.name, c.id] }
    end
    
    def create
      @listing = current_user.listings.build(listing_params)
      @listing.category_id = params[:category_id]
      if @listing.save
        redirect_to listings_path
      else
        render 'new'
      end
    end
    
    def edit
      @categories = Category.all.map{ |c| [c.name, c.id] }
    end
    
    def update
      @listing.category_id = params[:category_id]
      if @listing.update(listing_params)
        redirect_to listing_path(@listing)
      else
        render 'edit'
      end
    end
    
    def destroy
      @listing.destroy
      redirect_to root_path
    end
    
    private
    
    def listing_params
      params.require(:listing).permit(:title, :description, :price, :category_id)
    end
    
    def find_listing
      @listing = Listing.find(params[:id])
    end
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def full_title(page_title = '')
    base_title = "BridgeON" 
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="UTF-8">
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'shared/shim' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <%= render 'shared/header' %>
      <div class="notice"><%= notice %></div>
      <div class="alert"><%= alert %></div>
    <div class="wrapper"> 
      <div class="container">
        <div class="content">
          <%= yield %>
        </div>
      </div>
    </div>   
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/listings/_form.html.erb
<div class="form-horizontal">
  <fieldset>
    <legend>Add a listing</legend>
    <div class="form-inputs">
      <%= simple_form_for @listing, :html => { :multipart => true } do |f| %>
      <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a category") %>
      <%= f.input :title %>
      <%= f.input :description %>
      <%= f.input :price %>
      <%= f.button :submit, class: "form-actions" %>
    <% end %>
    </div>
  </fieldset>
</div>

app/views/listings/edit.html.erb
<div class="form-horizontal">
  <fieldset>
    <legend>Edit your listing</legend>
    <div class="form-inputs">
      <%= simple_form_for @listing, :html => { :multipart => true } do |f| %>
      <%= f.select :category_id, @categories %>
      <%= f.input :title %>
      <%= f.input :description %>
      <%= f.input :price %>
      <%= f.button :submit, class: "form-actions" %>
    <% end %>
    </div>
  </fieldset>
</div>

app/views/listings/index.html.erb
 <!-- Page Heading -->
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><%= params[:category] %>
        </h1>
    </div>
</div>
<!-- /.row -->

<% @listings.each do |listing| %>

<!-- Project one -->
<div class="row">
    <div class="col-md-7">
        <a href="#">
            <img class="img-responsive" src="http://placehold.it/700x300" alt="">
        </a>
    </div>
    <div class="col-md-5">
        <h3><%= link_to listing.title, listing_path(listing) %></h3>
        <h4>Description</h4>
        <p><%= listing.description %></p>
        <%= link_to '<span class="glyphicon glyphicon-chevron-right"></span> View listing'.html_safe, listing_path(listing), class: 'btn btn-primary' %>
    </div>
</div>
<!-- /.row -->

<hr>

<% end %>

<!-- Pagination -->
<div class="row text-center">
    <div class="col-lg-12">
        <ul class="pagination">
            <li>
                <a href="#">&laquo;</a>
            </li>
            <li class="active">
                <a href="#">1</a>
            </li>
            <li>
                <a href="#">2</a>
            </li>
            <li>
                <a href="#">3</a>
            </li>
            <li>
                <a href="#">4</a>
            </li>
            <li>
                <a href="#">5</a>
            </li>
            <li>
                <a href="#">&raquo;</a>
            </li>
        </ul>
    </div>
</div>
<!-- /.row -->

app/views/listings/new.html.erb
<% provide(:title,"Add a listing") %>

<%= render 'listings/form' %>

app/views/listings/show.html.erb
<ol class="breadcrumb", style="background: transparent;">
  <li><%= link_to "Home", root_path %></a></li>
  <li><a href="#">Library</a></li>
  <li class="active"><%= @listing.category.name %></li>
</ol>

<% if user_signed_in? %>
  <% if @listing.user_id == current_user.id %>
    <%= link_to 'Edit', edit_listing_path, class: "btn btn-default" %>
    <%= link_to 'Delete', listing_path(@listing), method: :delete, class: "btn btn-danger", data: { confirm: 'Are you sure?' }  %>
  <% end %>
<% end %>


<div class="col-md-12">

  <div class="thumbnail">
      <img class="img-responsive" src="http://placehold.it/800x500" alt=""><hr>
      <div class="caption-full">
          <h4 class="pull-right"><%= @listing.price %>$</h4>
          <h1><%= @listing.title %></h1><hr>
          <p><%= @listing.description %></p>
      </div>
  </div>

app/views/pages/about.html.erb
<% provide(:title, "About") %>

<h1 class="show-category"><%= params[:category] %></h1>

<% Category.all.each do |category| %>
	<li class="<%= 'active' if params[:category] == category.name %>">
		<%= link_to category.name, listings_path(category: category.name), class: "link" %>
	</li>
<% end %>

app/views/pages/index.html.erb
<!-- Page Heading -->
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Categories
        </h1>
    </div>
</div>
<!-- /.row -->

<!-- Projects Row -->
        <div class="row">
            <div class="col-md-3 portfolio-item">
                <a href="#">
                    <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                </a>
            </div>
            <div class="col-md-3 portfolio-item">
                <a href="#">
                    <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                </a>
            </div>
            <div class="col-md-3 portfolio-item">
                <a href="#">
                    <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                </a>
            </div>
            <div class="col-md-3 portfolio-item">
                <a href="#">
                    <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                </a>
            </div>
        </div>
        <!-- /.row -->

        <!-- Projects Row -->
        <div class="row">
            <div class="col-md-3 portfolio-item">
                <a href="#">
                    <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                </a>
            </div>
            <div class="col-md-3 portfolio-item">
                <a href="#">
                    <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                </a>
            </div>
            <div class="col-md-3 portfolio-item">
                <a href="#">
                    <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                </a>
            </div>
            <div class="col-md-3 portfolio-item">
                <a href="#">
                    <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                </a>
            </div>
        </div>
        <!-- /.row -->

        <!-- Projects Row -->
        <div class="row">
            <div class="col-md-3 portfolio-item">
                <a href="#">
                    <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                </a>
            </div>
            <div class="col-md-3 portfolio-item">
                <a href="#">
                    <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                </a>
            </div>
            <div class="col-md-3 portfolio-item">
                <a href="#">
                    <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                </a>
            </div>
            <div class="col-md-3 portfolio-item">
                <a href="#">
                    <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                </a>
            </div>
        </div>
        
        <!-- Projects Row -->
        <div class="row">
            <div class="col-md-3 portfolio-item">
                <a href="#">
                    <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                </a>
            </div>
            <div class="col-md-3 portfolio-item">
                <a href="#">
                    <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                </a>
            </div>
            <div class="col-md-3 portfolio-item">
                <a href="#">
                    <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                </a>
            </div>
            <div class="col-md-3 portfolio-item">
                <a href="#">
                    <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                </a>
            </div>
        </div>

app/views/shared/_footer.html.erb
<div id="footer">
  <div class="container">
    <hr><%= link_to "Terms and Conditions", "#", class: "a1" %> &nbsp;|&nbsp;
    <%= link_to "Contact Us", "#", class: "a1" %> &nbsp;|&nbsp;
    <%= link_to "Advertisement", "#", class: "a1" %> &nbsp;|&nbsp;
    <a href="https://github.com/AlvilsK/liston.git">GitHub</a> &nbsp;|&nbsp;
    Liston &copy; AlvilsK
  </div>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
      </button>
      <%= link_to "BridgeOn", root_path, class: "navbar-brand", style: "color:#990000; font-weight: bold;" %>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
         <li><%= link_to '<span class="glyphicon glyphicon-bullhorn"></span> SELL'.html_safe, new_listing_path, class: 'btn btn-default', style: "background: #990000;" %></li>
      </ul>
      <% if user_signed_in? %>
      <ul class="nav navbar-nav navbar-right">
         <li><%= link_to '<span class="glyphicon glyphicon-user"></span> Account'.html_safe, edit_user_registration_path, class: 'btn btn-default' %></li>
         <li><%= link_to '<span class="glyphicon glyphicon-log-out"></span> Log out'.html_safe, destroy_user_session_path, method: :delete, class: 'btn btn-default' %></li>
         <li class="s-icon" style="background:#990000;"><a href="#" id="addClass"><span class="glyphicon glyphicon-search"></span></a></li>
      </ul>
      <% else %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to '<span class="glyphicon glyphicon-user"></span> Sign up'.html_safe, new_user_registration_path, class: 'btn btn-default' %></li>
        <li class="divider"></li>
        <li><%= link_to '<span class="glyphicon glyphicon-log-in"></span> Log in'.html_safe, new_user_session_path, class: 'btn btn-default' %></li>
        <li class="s-icon" style="background:#990000;"><a href="#" id="addClass"><span class="glyphicon glyphicon-search"></span></a></li>
      </ul>
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->